# Generated by Django 3.0.5 on 2020-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Widht', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Shoulder', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Hand_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Hand_width', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
