# Generated by Django 3.0.5 on 2020-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Seat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Rise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Style', models.CharField(choices=[('Flat', 'flat'), ('single flit', 'single flit'), ('double flits', 'double flits')], max_length=50)),
                ('Fitting', models.CharField(choices=[('Regular fit', 'Regular fit'), ('Skinny fit', 'Skinny fit'), ('Slim fit', 'Slim fit'), ('Loose fir', 'Loose fit')], max_length=50)),
                ('Bottom', models.CharField(choices=[('Normal', 'Normal'), ('Bell', 'Bell'), ('Pencil', 'Pencil')], max_length=50)),
                ('Pocket_Style', models.CharField(choices=[('Straight', 'Straight'), ('Cross', 'Cross'), ('Jeans', 'Jeans')], max_length=50)),
                ('Remarks', models.CharField(max_length=50)),
            ],
        ),
    ]
