# Generated by Django 3.0.5 on 2020-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_pant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pant',
            name='Contact',
            field=models.CharField(max_length=10),
        ),
    ]
