# Generated by Django 3.0.5 on 2020-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200716_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='Contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
