# Generated by Django 3.0.5 on 2020-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200717_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pant',
            name='Status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Done', 'Done'), ('Delivered', 'Delivered')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='Status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Done', 'Done'), ('Delivered', 'Delivered')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
